# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fastailondon.github.io/ghost_ants/"

git_url = "https://github.com/fastailondon/ghost_ants/tree/master/"

def custom_doc_links(name): return None
